float:
  euclidean:
  - base_args: ['@metric']
    constructor: MariaDB
    disabled: false
    docker_tag: ann-benchmarks-mariadb
    module: ann_benchmarks.algorithms.mariadb
    name: mariadb
    run_groups:
      M-50:
        arg_groups: [{M: 50, efConstruction: 10}]
        args: {}
        query_args: [[10]]
      PGVector-default:
        arg_groups: [{M: 16, efConstruction: 64}]
        args: {}
        query_args: [[40]]
